{
 "title": "Weather",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "weather_temperature", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Apparent temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "weather_apparent_temperature", "legendFormat": "{{location}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Wind speed (m/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "weather_wind_speed", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Cloud cover (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "weather_cloud_cover", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "{{location}}" }
   ]
  }
 ]
}